---
- hosts: all
  tasks:
    - name: 'atualizando repos'
      apt:
        update_cache: yes
      become: yes
    - name: 'Instalando php5'
      apt:
        name: php5
        state: latest
      become: yes
    - name: 'Instalando apache2'
      apt: 
        name: apache2
        state: latest
      become: yes
    - name: 'Instala modphp'
      apt: 
        name: libapache2-mod-php5
        state: latest
      become: yes